import { ProfileSurveyQuestion } from "../types/Profile";

// need to change for production
export const API_URL = "https://146.190.125.251:8000/api";
export const surveyQuestions: Array<ProfileSurveyQuestion> = [
  {
    variableId: "age",
    prettyName: "Age",
    question: "Enter your age",
    hasQuantitative: true,
    unit: "years",
    qualitativeOptions: [],
    required: true,
    mean: 50,
    stdev: 15,
  },
  {
    variableId: "gait_speed",
    prettyName: "Gait Speed",
    question: "Enter your average gait speed",
    hasQuantitative: true,
    unit: "m/s",
    qualitativeOptions: [
      "Unable to walk",
      "Extremely slow",
      "Slow",
      "Average",
      "Fast",
      "Extremely fast",
    ],
    required: false,
    mean: 0.853874057544418,
    stdev: 0.28451581955254013,
  },
  {
    variableId: "grip_dom",
    prettyName: "Dominant Hand Grip Strength",
    question: "Enter the grip strength of your dominant hand",
    hasQuantitative: true,
    unit: "lbs",
    qualitativeOptions: [
      "Very weak",
      "Weak",
      "Average",
      "Strong",
      "Very strong",
    ],
    required: false,
    mean: 28.436364178481274,
    stdev: 11.308967992782993,
  },
  {
    variableId: "grip_ndom",
    prettyName: "Non-Dominant Hand Grip Strength",
    question: "Enter the grip strength of your non-dominant hand",
    hasQuantitative: true,
    unit: "lbs",
    qualitativeOptions: [
      "Very weak",
      "Weak",
      "Average",
      "Strong",
      "Very strong",
    ],
    required: false,
    mean: 26.07880308937994,
    stdev: 10.5158958288211,
  },
  {
    variableId: "FI_ADL",
    prettyName: "ADL Score",
    question: "Enter your ADL score",
    // "Any difficulty in the last 3 months because of physical, mental, emotional, or memory problems: (a) dressing (including putting on shoes and socks), (b) eating (such as cutting up your food), (c) using the toilet (including getting up and down), (d) bathing and showering, (e) getting in and out of bed, and (f) walking across a room",
    hasQuantitative: false,
    unit: "sum",
    qualitativeOptions: ["1", "2", "3", "4", "5", "6"],
    required: false,
    mean: 0.20268848442975199,
    stdev: 0.26173694862441804,
  },
  {
    variableId: "FI_IADL",
    prettyName: "IADL Score",
    question: "Enter your IADL score",
    // "Any difficulty in the last 3 months because of physical, mental, emotional, or memory problems: (a) preparing a hot meal, (b) shopping for groceries, (c) making telephone calls, (d) taking medications, and (e) managing your money, such as paying your bills and keeping track of expenses",
    hasQuantitative: false,
    unit: "sum",
    qualitativeOptions: ["1", "2", "3", "4", "5"],
    required: false,
    mean: 0.06808106625950425,
    stdev: 0.1567108755355969,
  },
  {
    variableId: "chair",
    prettyName: "Chair Raises",
    question:
      "Stand up from a firm straight-backed chair, fold your arms across your chest and sit so that your feet are on the floor; then stand up keeping your arms folded across your chest. Enter the number of seconds it takes to repeat this excercise 5 times",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "Extremely slow",
      "Slow",
      "Average",
      "Fast",
      "Extremely fast",
    ],
    required: false,
    mean: 11.535945600583949,
    stdev: 4.220377324322096,
  },
  {
    variableId: "leg_raise",
    prettyName: "Leg Raise",
    question:
      "Try to stand on one leg and raise the other leg off the ground a few inches. You may use your arms, bend your knees, or move your body to maintain your balance, but try not to move your feet. You may support yourself on a chair, table or wall while getting into position. Enter how long you can hold this stance, up to 30 seconds",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "Less than half duration",
      "More than half duration",
      "Full duration",
    ],
    required: false,
    mean: 16,
    stdev: 5.5,
  },
  {
    variableId: "full_tandem",
    prettyName: "Full Tandem Stance",
    question:
      "Tandem stance: Stand side by side with your feet together and hold for up to 30 seconds. Stop timing when you step out of position or grab something for assistance. Enter the amount of time you can hold this stance",
    hasQuantitative: true,
    unit: "sec",
    qualitativeOptions: [
      "Less than half duration",
      "More than half duration",
      "Full duration",
    ],
    required: false,
    mean: 2.070456640118188,
    stdev: 0.7301471469371483,
  },
  {
    variableId: "srh",
    prettyName: "Self-Rated Health",
    question: "How would you rate your overall health",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Excellent", "Very good", "Good", "Fair", "Poor"],
    required: false,
    mean: 0.4033145172962802,
    stdev: 0.27757305612048716,
  },
  {
    variableId: "eye",
    prettyName: "Self-Rated Eyesight",
    question: "How would you rate your eyesight",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: [
      "Excellent",
      "Very good",
      "Good",
      "Fair",
      "Poor",
      "Registered/legally blind",
    ],
    required: false,
    mean: 0.31634668892617235,
    stdev: 0.20057904741917865,
  },
  {
    variableId: "hear",
    prettyName: "Self-Rated Hearing",
    question: "How would you rate your hearing?",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Excellent", "Very good", "Good", "Fair", "Poor"],
    required: false,
    mean: 0.4104753227242377,
    stdev: 0.2797723245182508,
  },
  {
    variableId: "func",
    prettyName: "Difficulty Walking",
    question:
      "How much difficulty do you have walking a quarter mile by yourself and without special equipment",
    hasQuantitative: false,
    unit: "sec",
    qualitativeOptions: [
      "No difficulty",
      "Some difficulty",
      "Much difficulty",
      "Unable",
    ],
    required: false,
    mean: 0.1959890102227365,
    stdev: 0.3391606567006017,
  },
  {
    variableId: "dias",
    prettyName: "Diastolic Blood Pressure",
    question: "Enter your diastolic blood pressure",
    hasQuantitative: true,
    unit: "mmHg",
    qualitativeOptions: [
      "Extremely low",
      "Low",
      "Average",
      "High",
      "Extremely high",
    ],
    required: false,
    mean: 75.76050022511951,
    stdev: 12.704728759608257,
  },
  {
    variableId: "sys",
    prettyName: "Systolic Blood Pressure",
    question: "Enter your systolic blood pressure",
    hasQuantitative: true,
    unit: "mmHg",
    qualitativeOptions: [
      "Extremely low",
      "Low",
      "Average",
      "High",
      "Extremely high",
    ],
    required: false,
    mean: 137.76928908123554,
    stdev: 20.270871864472632,
  },
  {
    variableId: "pulse",
    prettyName: "Pulse",
    question: "Enter your pulse",
    hasQuantitative: true,
    unit: "bpm",
    qualitativeOptions: [
      "Extremely low",
      "Low",
      "Average",
      "High",
      "Extremely high",
    ],
    required: false,
    mean: 68.42104803653973,
    stdev: 11.285062475935565,
  },
  {
    variableId: "trig",
    prettyName: "Blood Triglyceride Level",
    question: "Enter your blood triglyceride level",
    // "Together with total and HDL cholesterol, they provide a lipid profile that can give information on the risk of cardiovascular disease",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Normal", // Less than 150 mg/dL (1.69 mmol/L)",
      "Borderline high", //: 150 to 199 mg/dL (1.69 to 2.25 mmol/L)",
      "High", //: 200 to 499 mg/dL (2.26 to 5.64 mmol/L)",
      "Very high", //: 500 mg/dL or above (5.65 mmol/L)",
    ],
    required: false,
    mean: 0.37934330777806136,
    stdev: 0.5011242623973755,
  },
  {
    variableId: "crp",
    prettyName: "Blood CRP Level",
    question: "Enter your blood CRP level",
    // "The level of this protein in the blood gives information on inflammatory activity in the body, and it is also associated with risk of heart disease",
    hasQuantitative: true,
    unit: "mg/L",
    qualitativeOptions: [
      "Normal", //: Less than 0.3 mg/dL",
      "Minor elevation", //: 0.3 to 1.0 mg/dL",
      "Moderate elevation", //: 1.0 to 10.0 mg/d",
      "Marked elevation", //: More than 10.0 mg/dL",
      "Severe elevation", //: More than 50.0 mg/dL",
    ],
    required: false,
    mean: 0.6397056535068669,
    stdev: 1.1353660719205658,
  },
  {
    variableId: "hdl",
    prettyName: "Blood HDL Level",
    question: "Enter your blood HDL level",
    // "This is ‘good’ cholesterol, which is protective for heart disease. Triglycerides - Together with total and HDL cholesterol, they provide a lipid profile that can give information on the risk of cardiovascular disease",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Excellent", //: 60 mg/dL (1.5 mmol/L) or higher",
      "Average", //: 40-59 mg/dL (1-1.5 mmol/L)",
      "Low", //: less than 40 mg/dL (1.03 mmol/L)",
    ],
    required: false,
    mean: 1.5468664148351616,
    stdev: 0.44133941424915846,
  },
  {
    variableId: "ldl",
    prettyName: "Blood LDL Level",
    question: "Enter your blood LDL level",
    // "This is ‘bad’ cholesterol; increased levels are associated with atherosclerosis, and thus myocardial infarctions, strokes and peripheral vascular disease",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Very High", //: 190 mg/dL (4.9 mmol/L) or high with coronary artery disease",
      "High", //: 160-189 mg/dL (3.4 - 4.9 mmol/L) or  borderline high or near optimal with coronary artery disease",
      "Near Optimal", //: 100 -129 mg/dL (2.6-3.3 mmol/L) or optimal with coronary artery disease",
      "Optimal", //: Below 100 mg/dL (Below 2.6 mmol/L)",
      "Best", //: Below 70 mg/dL (Below 1.8 mmol/L)",
    ],
    required: false,
    mean: 3.300098459399978,
    stdev: 1.0527448115035516,
  },
  {
    variableId: "glucose",
    prettyName: "Blood Glucose Level",
    question: "Enter your blood glucose level",
    // "Blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Normal Fasting blood sugar level", //: 100 mg/dL (5.6 mmol/L)",
      "High", //: 160-189 mg/dL (3.4 - 4.9 mmol/L) or  borderline high or near optimal with coronary artery disease",
      "Near Optimal", //: 100 -129 mg/dL (2.6-3.3 mmol/L) or optimal with coronary artery disease",
      "Optimal", //: Below 100 mg/dL (Below 2.6 mmol/L)",
      "Best", //: Below 70 mg/dL (Below 1.8 mmol/L)",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "igf1",
    prettyName: "Insulin-Like Growth Factor",
    question: "Enter your insulin-like growth factor (IGF-1)",
    // "These are hormones that help control reactions to stress and regulate various body processesincluding digestion, the immune system, mood, and energy usage",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: 182 to 780 ng/mL for ages 16 to 24 114 to 492 ng/mL for ages 25 to 39 90 to 360 ng/mL for ages 40 to 54",
      "Above normal",
    ],
    required: false,
    mean: 20.0,
    stdev: 5,
  },
  {
    variableId: "hgb",
    prettyName: "Blood Hemoglobin Level",
    question: "Enter your blood hemoglobin level",
    // "These are measures of iron levels in the body and are related to diet and other factors",
    hasQuantitative: true,
    unit: "g/dl",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: Male: 13.8 to 17.2 grams per deciliter (g/dL) Female: 12.1 to 15.1 (g/dL)",
      "Above normal",
    ],
    required: false,
    mean: 15,
    stdev: 3,
  },
  {
    variableId: "fib",
    prettyName: "Blood Fibrinogen Level",
    question: "Enter your blood fibrinogen level",
    // "A protein necessary for blood clotting. High levels are also associated with a higher risk of heart disease",
    hasQuantitative: true,
    unit: "g/L",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: Between 200 and 400 mg/dL ",
      "Above normal",
    ],
    required: false,
    mean: 3,
    stdev: 1,
  },
  {
    variableId: "fer",
    prettyName: "Blood Ferritin Level",
    question: "Enter your blood ferritin level",
    // "These are measures of iron levels in the body and are related to diet and other factors",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: (Male) 12 to 300 ng/mL, (Female) 12 to 150 ng/mL",
      "Above normal",
    ],
    required: false,
    mean: 150,
    stdev: 50,
  },
  {
    variableId: "chol",
    prettyName: "Blood Total Cholesterol Level",
    question: "Enter your blood total cholesterol level",
    // "Cholesterol is a type of fat present in the blood, related to diet. Too much cholesterol in the blood increases the risk of heart disease",
    hasQuantitative: true,
    unit: "mmol/L",
    qualitativeOptions: [
      "Normal", //:  less than 200 mg/dL (5.17 mmol/L)",
      "Borderline high", //: 200 to 239 mg/dL (5.17 to 6.18 mmol/L)",
      "High", //:  240 mg/dL (6.21 mmol/L) or greater",
    ],
    required: false,
    mean: 140,
    stdev: 75,
  },
  {
    variableId: "wbc",
    prettyName: "White Blood Cell Count",
    question: "Enter your white blood cell count",
    // "When looked in combination with ferritin and hemoglobin can indicate anemia",
    hasQuantitative: true,
    unit: "billions/L",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: 4.5 to 11.0 billion/L",
      "Above normal",
    ],
    required: false,
    mean: 7.5,
    stdev: 4,
  },
  {
    variableId: "mch",
    prettyName: "Blood Mean Corpuscular Hemoglobin Level",
    question: "Enter your blood mean corpuscular hemoglobin (MCH) level",
    // "When looked in combination with ferritin and hemoglobin can indicate anemia",
    hasQuantitative: true,
    unit: "pg/cell",
    qualitativeOptions: [
      "Below normal",
      "Normal", //: 320 to 360 grams per liter (g/L)",
      "Above normal",
    ],
    required: false,
    mean: 30,
    stdev: 10,
  },
  {
    variableId: "hba1c",
    prettyName: "Blood Glycated Hemoglobin Level",
    question: "Enter your blood glycated hemoglobin (HbA1c) level",
    // "Indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease",
    hasQuantitative: true,
    unit: "%",
    qualitativeOptions: [
      "Normal", //: Less than 5.7%",
      "Prediabetes", //: 5.7% to 6.4%",
      "Diabetes", //: 6.5% or higher",
    ],
    required: false,
    mean: 4,
    stdev: 2,
  },
  {
    variableId: "vitd",
    prettyName: "Vitamin D Level",
    question: "Enter your vitamin D level",
    // "Obtained from the diet and from sunshine, Vitamin D is needed for healthy bones",
    hasQuantitative: true,
    unit: "nmol/L",
    qualitativeOptions: [
      "Deficiency", //: less than 30 nmol/L (12 ng/mL)",
      "Potential deficiency", //: between 30 nmol/L (12 ng/mL) and 50 nmol/L (20 ng/mL)",
      "Normal levels", //: between 50 nmol/L (20 ng/mL) and 125 nmol/L (50 ng/mL)",
      "High", //: higher than 125 nmol/L (50 ng/mL)",
    ],
    required: false,
    mean: 90,
    stdev: 40,
  },
  {
    variableId: "BP med",
    prettyName: "Blood Pressure Medication",
    question: "Are you taking medication for blood pressure",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "anticoagulent med",
    prettyName: "Anticoagulent Medication",
    question: "Are you taking an anticoagulant medication, such as warfarin",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "chol med",
    prettyName: "Cholesterol Medication",
    question:
      "Are you taking medicine to lower cholesterol or prevent cholesterol from getting high",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "hip/knee treat",
    prettyName: "Hip/Knee Treatment",
    question:
      "Do you take medication or calcium/vitamin D pills for osteoporosis",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "lung/asthma med",
    prettyName: "Lung/Asthma Medication",
    question:
      "Are you taking meditation to treat lung condition or to prevent the return of a lung condition",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "longill",
    prettyName: "Long Illness",
    question: "Do you have any long-standing illness, disability or infirmity",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "limitact",
    prettyName: "Limit Activity",
    question: "Does any illness or disability limit your activities in any way",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "effort",
    prettyName: "Effort Level",
    question:
      "For much of the time during the past week, have you felt that everything you did was an effort",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "smkevr",
    prettyName: "Smoking",
    question: "Have you ever smoked cigarettes",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "smknow",
    prettyName: "Current Smoking",
    question: "Do you smoke cigarettes at all nowadays",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "mobility",
    prettyName: "Mobility",
    question: "How would you describe your mobility",
    // "blood glucose levels indicate the presence or risk of type 2 diabetes, which is associated with an increased risk of heart disease",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: [
      "Can walk without using another person or support",
      "Can walk with help of another person or using support",
      "In wheelchair",
      "Bed bound",
      "Unknown",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "country",
    prettyName: "Country",
    question: "Were you born inside or outside the UK",
    // "ELSA Country of birth collapsed into UK and elsewhere to avoid disclosure",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["UK", "outside UK"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "alcohol",
    prettyName: "Alcohol Consumption",
    question: "How would you describe your alcohol consumption",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: [
      "Twice a day or more",
      "Daily or almost daily",
      "Once or twice a week",
      "Once or twice a month",
      "Special occasions only",
      "Not at all",
    ],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "jointrep",
    prettyName: "Joint Replacement",
    question: "Have you ever had any joint replacements",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "fractures",
    prettyName: "Hip Fractures",
    question: "Have you ever fractured your hip",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Yes", "No"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "height",
    prettyName: "Height",
    question: "Enter your height",
    hasQuantitative: true,
    unit: "cm",
    qualitativeOptions: ["Very Short", "Short", "Average", "Tall", "Very Tall"],
    required: false,
    mean: 182,
    stdev: 20,
  },
  {
    variableId: "bmi",
    prettyName: "BMI",
    question: "Enter your BMI",
    hasQuantitative: true,
    unit: "kg/m²",
    qualitativeOptions: [
      "Underweight",
      "Healthy weight",
      "Overweight",
      "Obese",
    ],
    required: false,
    mean: 27.781513821745225,
    stdev: 4.853978745570567,
  },
  {
    variableId: "ethnicity",
    prettyName: "Ethnicity",
    question: "Are you white or non-white",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["White", "Non-White"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
  {
    variableId: "sex",
    prettyName: "Sex",
    question: "What is your sex",
    hasQuantitative: false,
    unit: "N/A",
    qualitativeOptions: ["Male", "Female"],
    required: false,
    mean: 5.088684834123225,
    stdev: 0.9870697209153416,
  },
] as const;

export const PRED_DT = 0.5;

export const graphDomains = [5, 10, 20, 50];
